// This file generated by `scripts/code_generators.ts#generateActionsRequireFile`
// Don't modify it

import * as googleLogin from './google_login'
export { googleLogin }

export type Actions =
  | googleLogin.Actions

export type State =
  & googleLogin.State

import { compose } from 'redux'
export const reducer = compose(
  googleLogin.reducer,
)
import { combineEpics } from 'redux-observable'
export const epic = combineEpics(
  googleLogin.epic,
)
